import { trpc } from "@/lib/trpc";
import { cn } from "@/lib/utils";
import { toast } from "sonner";
import { Loader2, CheckCircle2, MessageCircle, Copy, Trash2, Zap, AlertTriangle, Clock, User, BellOff } from "lucide-react";
import { Reminder, TYPE_CONFIG, STATUS_CONFIG, formatScheduled, openWhatsApp } from "./types";

interface Props {
  reminder: Reminder;
  onDelete: () => void;
}

export function ReminderCard({ reminder, onDelete }: Props) {
  const utils = trpc.useUtils();
  const typeConf = TYPE_CONFIG[reminder.type];
  const statusConf = STATUS_CONFIG[reminder.status];
  const TypeIcon = typeConf.icon;
  const StatusIcon = statusConf.icon;
  const scheduled = new Date(reminder.scheduledAt);
  const isPast = scheduled < new Date();
  
  const isDelayed = isPast && reminder.status === "pendente";

  const markSent = trpc.reminders.markSent.useMutation({
    onSuccess: () => { utils.reminders.list.invalidate(); utils.reminders.pendingCount.invalidate(); toast.success("Marcado como enviado!"); },
    onError: (e) => toast.error("Erro: " + e.message),
  });
  const cancel = trpc.reminders.cancel.useMutation({
    onSuccess: () => { utils.reminders.list.invalidate(); utils.reminders.pendingCount.invalidate(); toast.success("Lembrete cancelado"); },
    onError: (e) => toast.error("Erro: " + e.message),
  });

  const copyMsg = () => { navigator.clipboard.writeText(reminder.message); toast.success("Mensagem copiada!"); };

  const finalColorBorder = isDelayed 
    ? "border-red-300 dark:border-red-900 shadow-sm shadow-red-500/10" 
    : reminder.status === "enviado" 
      ? "border-emerald-200 dark:border-emerald-900/50" 
      : reminder.status === "cancelado" ? "border-border opacity-60" 
      : "border-border hover:border-primary/30 hover:shadow-md";

  return (
    <div className={cn(
      "group relative flex flex-col bg-card rounded-2xl border transition-all duration-300 overflow-hidden",
      finalColorBorder
    )}>
      {isDelayed && (
        <div className="absolute top-0 right-0 w-24 h-24 overflow-hidden rounded-tr-2xl z-0 pointer-events-none">
          <div className="absolute top-4 -right-8 w-32 h-6 bg-red-500 text-[10px] uppercase font-black text-white text-center flex items-center justify-center rotate-45 shadow-sm">
            Atrasado
          </div>
        </div>
      )}

      {/* Header section */}
      <div className={cn("flex flex-wrap items-center justify-between p-3 border-b border-border/50 bg-muted/20 gap-2")}>
        <div className="flex items-center gap-2 z-10">
          <div className={cn("p-1.5 rounded-lg", typeConf.bg)}>
            <TypeIcon size={14} className={typeConf.color} />
          </div>
          <span className={cn("text-[11px] font-bold uppercase tracking-wider", typeConf.color)}>
            {typeConf.label}
          </span>
          <span className={cn("text-[10px] font-bold px-2 py-0.5 rounded-full flex items-center gap-1 border", statusConf.bg, statusConf.color, "border-transparent")}>
            <StatusIcon size={10} /> {statusConf.label}
          </span>
          {reminder.autoGenerated === 1 && (
            <span className="text-[10px] text-primary bg-primary/10 px-2 py-0.5 rounded-full font-bold flex items-center gap-1">
              <Zap size={10} /> Auto
            </span>
          )}
        </div>
        <div className={cn("text-[11px] font-medium flex items-center gap-1 z-10", isDelayed ? "text-red-500 font-bold" : "text-muted-foreground")}>
          {isDelayed ? <AlertTriangle size={12} /> : <Clock size={12} />}
          {formatScheduled(scheduled)}
        </div>
      </div>

      {/* Body section */}
      <div className="p-4 flex-1">
        {reminder.studentName ? (
           <div className="flex items-center gap-1.5 mb-2">
             <div className="w-5 h-5 rounded-full bg-primary/10 flex items-center justify-center">
               <User size={10} className="text-primary" />
             </div>
             <p className="text-xs font-bold text-foreground">{reminder.studentName}</p>
           </div>
        ) : (
           <p className="text-xs font-semibold text-muted-foreground mb-2 flex items-center gap-1.5">
             <User size={12} /> Aluno não vinculado
           </p>
        )}
        <p className="text-xs text-muted-foreground line-clamp-3 leading-relaxed mt-1 bg-muted/30 p-2.5 rounded-xl border border-transparent group-hover:border-border transition-colors">
          {reminder.message}
        </p>
      </div>

      {/* Actions section */}
      <div className="p-3 pt-0 flex items-center gap-2 flex-wrap">
        {reminder.status === "pendente" && (
          <>
            <button
              onClick={() => openWhatsApp(reminder.studentPhone, reminder.message, toast.error)}
              className="flex-1 min-w-[120px] flex items-center justify-center gap-1.5 text-xs font-bold px-3 py-2 rounded-xl bg-gradient-to-r from-emerald-500 to-emerald-600 text-white hover:from-emerald-400 hover:to-emerald-500 shadow-sm shadow-emerald-500/20 transition-all hover:scale-[1.02]">
              <MessageCircle size={14} /> Enviar WhatsApp
            </button>
            <button onClick={() => markSent.mutate({ id: reminder.id })} disabled={markSent.isPending}
              className="px-3 py-2 flex items-center gap-1.5 text-xs font-bold bg-primary/10 text-primary hover:bg-primary/20 rounded-xl transition-colors">
              {markSent.isPending ? <Loader2 size={13} className="animate-spin" /> : <CheckCircle2 size={13} />} Concluir
            </button>
            <button onClick={() => cancel.mutate({ id: reminder.id })} disabled={cancel.isPending}
              className="px-3 py-2 flex items-center gap-1.5 text-xs font-bold text-muted-foreground hover:bg-red-100 hover:text-red-600 dark:hover:bg-red-950/50 rounded-xl transition-colors">
              <BellOff size={13} /> Cancelar
            </button>
          </>
        )}
        {(reminder.status === "enviado" || reminder.status === "cancelado") && (
          <button onClick={copyMsg}
            className="flex-1 flex items-center justify-center gap-1.5 text-xs font-bold px-3 py-2 rounded-xl bg-muted/50 text-foreground hover:bg-muted transition-colors">
            <Copy size={13} /> Copiar texto
          </button>
        )}
        <button onClick={onDelete}
          className="w-10 h-9 flex items-center justify-center text-muted-foreground hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-950/50 rounded-xl transition-colors ml-auto">
          <Trash2 size={14} />
        </button>
      </div>
    </div>
  );
}
