import { BookOpen, CreditCard, AlertTriangle, ListTodo, Clock, CheckCircle2, Ban } from "lucide-react";

export type ReminderType = "aula" | "cobranca" | "inadimplencia" | "manual";
export type ReminderStatus = "pendente" | "enviado" | "cancelado";

export type Reminder = {
  id: number;
  type: ReminderType;
  message: string;
  scheduledAt: Date | string;
  status: ReminderStatus;
  autoGenerated: number;
  sentAt?: Date | string | null;
  cancelledAt?: Date | string | null;
  studentId?: number | null;
  studentName?: string | null;
  studentPhone?: string | null;
  lessonId?: number | null;
  paymentDueId?: number | null;
};

export type Template = {
  id: number;
  name: string;
  type: ReminderType;
  body: string;
  isDefault: number;
};

export const TYPE_CONFIG: Record<ReminderType, { label: string; icon: React.ElementType; color: string; bg: string; border: string }> = {
  aula:         { label: "Aula",         icon: BookOpen,    color: "text-blue-600 dark:text-blue-400",    bg: "bg-blue-50 dark:bg-blue-950/30",    border: "border-blue-200 dark:border-blue-800" },
  cobranca:     { label: "Cobrança",     icon: CreditCard,  color: "text-emerald-600 dark:text-emerald-400", bg: "bg-emerald-50 dark:bg-emerald-950/30", border: "border-emerald-200 dark:border-emerald-800" },
  inadimplencia:{ label: "Inadimplência",icon: AlertTriangle,color: "text-red-600 dark:text-red-400",     bg: "bg-red-50 dark:bg-red-950/30",      border: "border-red-200 dark:border-red-800" },
  manual:       { label: "Manual",       icon: ListTodo,    color: "text-violet-600 dark:text-violet-400", bg: "bg-violet-50 dark:bg-violet-950/30", border: "border-violet-200 dark:border-violet-800" },
};

export const STATUS_CONFIG: Record<ReminderStatus, { label: string; color: string; bg: string; icon: React.ElementType }> = {
  pendente:  { label: "Pendente",  color: "text-amber-700 dark:text-amber-400",  bg: "bg-amber-100 dark:bg-amber-900/30",  icon: Clock },
  enviado:   { label: "Enviado",   color: "text-emerald-700 dark:text-emerald-400", bg: "bg-emerald-100 dark:bg-emerald-900/30", icon: CheckCircle2 },
  cancelado: { label: "Cancelado", color: "text-slate-500",                       bg: "bg-slate-100 dark:bg-slate-800",     icon: Ban },
};

export const VARIABLES_HELP = ["{nome}", "{instrumento}", "{data_aula}", "{hora_aula}", "{valor}", "{vencimento}"];

export function formatScheduled(date: Date | string) {
  const now = new Date();
  const d = new Date(date);
  const isToday = d.toDateString() === now.toDateString();
  const tomorrow = new Date(now); tomorrow.setDate(now.getDate() + 1);
  const isTomorrow = d.toDateString() === tomorrow.toDateString();
  const time = d.toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" });
  if (isToday) return `Hoje às ${time}`;
  if (isTomorrow) return `Amanhã às ${time}`;
  return d.toLocaleDateString("pt-BR", { day: "2-digit", month: "short", year: "numeric" }) + ` às ${time}`;
}

export function openWhatsApp(phone: string | null | undefined, message: string, onError: (err: string) => void) {
  if (!phone) { onError("Aluno sem número de telefone cadastrado"); return; }
  const digits = phone.replace(/\D/g, "");
  const num = digits.startsWith("55") ? digits : `55${digits}`;
  const url = `https://wa.me/${num}?text=${encodeURIComponent(message)}`;
  window.open(url, "_blank");
}
