import { describe, it, expect, vi, beforeEach } from "vitest";
import { appRouter } from "./routers";
import type { TrpcContext } from "./_core/context";

// ─── Mock DB ──────────────────────────────────────────────────────────────────
vi.mock("./db", () => ({
  getDb: vi.fn(),
  upsertUser: vi.fn(),
  getUserByOpenId: vi.fn(),
  getSettingsByUserId: vi.fn(),
  upsertSettings: vi.fn(),
  updateUserProfile: vi.fn(),
}));

import { getDb } from "./db";

type AuthUser = NonNullable<TrpcContext["user"]>;

function makeCtx(): TrpcContext {
  const user: AuthUser = {
    id: 1,
    openId: "test-user",
    email: "prof@musicpro.com",
    name: "Professor Teste",
    loginMethod: "manus",
    role: "user",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastSignedIn: new Date(),
  };
  return {
    user,
    req: { protocol: "https", headers: {} } as TrpcContext["req"],
    res: { clearCookie: vi.fn() } as unknown as TrpcContext["res"],
  };
}

// ─── Helper: mock DB object ───────────────────────────────────────────────────
function makeDb(overrides: Record<string, unknown> = {}) {
  const chain = {
    select: vi.fn().mockReturnThis(),
    from: vi.fn().mockReturnThis(),
    where: vi.fn().mockReturnThis(),
    leftJoin: vi.fn().mockReturnThis(),
    orderBy: vi.fn().mockResolvedValue([]),
    limit: vi.fn().mockResolvedValue([]),
    insert: vi.fn().mockReturnThis(),
    values: vi.fn().mockResolvedValue(undefined),
    update: vi.fn().mockReturnThis(),
    set: vi.fn().mockReturnThis(),
    delete: vi.fn().mockReturnThis(),
    ...overrides,
  };
  return chain;
}

// ─── Tests ────────────────────────────────────────────────────────────────────
describe("reminders.pendingCount", () => {
  it("returns 0 when db is unavailable", async () => {
    (getDb as ReturnType<typeof vi.fn>).mockResolvedValue(null);
    const caller = appRouter.createCaller(makeCtx());
    const count = await caller.reminders.pendingCount();
    expect(count).toBe(0);
  });

  it("returns the number of pending reminders", async () => {
    const db = makeDb({
      where: vi.fn().mockResolvedValue([{ id: 1 }, { id: 2 }]),
    });
    (getDb as ReturnType<typeof vi.fn>).mockResolvedValue(db);
    const caller = appRouter.createCaller(makeCtx());
    const count = await caller.reminders.pendingCount();
    expect(count).toBe(2);
  });
});

describe("reminders.list", () => {
  it("returns empty array when db is unavailable", async () => {
    (getDb as ReturnType<typeof vi.fn>).mockResolvedValue(null);
    const caller = appRouter.createCaller(makeCtx());
    const list = await caller.reminders.list();
    expect(list).toEqual([]);
  });

  it("returns filtered list by type", async () => {
    const mockRows = [
      { id: 1, type: "aula", message: "Lembrete aula", scheduledAt: new Date(), status: "pendente", autoGenerated: 1, sentAt: null, cancelledAt: null, refId: null, studentId: 1, lessonId: 1, paymentDueId: null, createdAt: new Date(), studentName: "João", studentPhone: "11999999999" },
      { id: 2, type: "cobranca", message: "Lembrete cobrança", scheduledAt: new Date(), status: "pendente", autoGenerated: 1, sentAt: null, cancelledAt: null, refId: null, studentId: 2, lessonId: null, paymentDueId: 1, createdAt: new Date(), studentName: "Maria", studentPhone: null },
    ];
    const db = makeDb({ orderBy: vi.fn().mockResolvedValue(mockRows) });
    (getDb as ReturnType<typeof vi.fn>).mockResolvedValue(db);
    const caller = appRouter.createCaller(makeCtx());
    const list = await caller.reminders.list({ type: "aula" });
    expect(list).toHaveLength(1);
    expect(list[0].type).toBe("aula");
  });
});

describe("reminders.create", () => {
  it("creates a manual reminder", async () => {
    const db = makeDb();
    (getDb as ReturnType<typeof vi.fn>).mockResolvedValue(db);
    const caller = appRouter.createCaller(makeCtx());
    const result = await caller.reminders.create({
      type: "manual",
      message: "Lembrete de teste",
      scheduledAt: new Date(Date.now() + 86400000).toISOString(),
    });
    expect(result).toEqual({ success: true });
    expect(db.insert).toHaveBeenCalled();
    expect(db.values).toHaveBeenCalled();
  });

  it("throws when db is unavailable", async () => {
    (getDb as ReturnType<typeof vi.fn>).mockResolvedValue(null);
    const caller = appRouter.createCaller(makeCtx());
    await expect(
      caller.reminders.create({ type: "manual", message: "Teste", scheduledAt: new Date().toISOString() })
    ).rejects.toThrow("Database not available");
  });
});

describe("reminders.markSent", () => {
  it("marks a reminder as sent", async () => {
    const db = makeDb();
    (getDb as ReturnType<typeof vi.fn>).mockResolvedValue(db);
    const caller = appRouter.createCaller(makeCtx());
    const result = await caller.reminders.markSent({ id: 1 });
    expect(result).toEqual({ success: true });
    expect(db.update).toHaveBeenCalled();
    expect(db.set).toHaveBeenCalled();
  });
});

describe("reminders.cancel", () => {
  it("cancels a reminder", async () => {
    const db = makeDb();
    (getDb as ReturnType<typeof vi.fn>).mockResolvedValue(db);
    const caller = appRouter.createCaller(makeCtx());
    const result = await caller.reminders.cancel({ id: 1 });
    expect(result).toEqual({ success: true });
    expect(db.update).toHaveBeenCalled();
  });
});

describe("reminders.delete", () => {
  it("deletes a reminder", async () => {
    const db = makeDb();
    (getDb as ReturnType<typeof vi.fn>).mockResolvedValue(db);
    const caller = appRouter.createCaller(makeCtx());
    const result = await caller.reminders.delete({ id: 1 });
    expect(result).toEqual({ success: true });
    expect(db.delete).toHaveBeenCalled();
  });
});

describe("reminderTemplates.list", () => {
  it("returns empty array when db is unavailable", async () => {
    (getDb as ReturnType<typeof vi.fn>).mockResolvedValue(null);
    const caller = appRouter.createCaller(makeCtx());
    const list = await caller.reminderTemplates.list();
    expect(list).toEqual([]);
  });

  it("returns templates from db", async () => {
    const mockTemplates = [
      { id: 1, userId: 1, name: "Padrão Aula", type: "aula", body: "Olá {nome}, aula amanhã!", isDefault: 1, createdAt: new Date(), updatedAt: new Date() },
    ];
    const db = makeDb({ orderBy: vi.fn().mockResolvedValue(mockTemplates) });
    (getDb as ReturnType<typeof vi.fn>).mockResolvedValue(db);
    const caller = appRouter.createCaller(makeCtx());
    const list = await caller.reminderTemplates.list();
    expect(list).toHaveLength(1);
    expect(list[0].name).toBe("Padrão Aula");
  });
});

describe("reminderTemplates.create", () => {
  it("creates a template", async () => {
    const db = makeDb({
      where: vi.fn().mockReturnThis(),
      set: vi.fn().mockReturnThis(),
      update: vi.fn().mockReturnThis(),
    });
    (getDb as ReturnType<typeof vi.fn>).mockResolvedValue(db);
    const caller = appRouter.createCaller(makeCtx());
    const result = await caller.reminderTemplates.create({
      name: "Template Aula",
      type: "aula",
      body: "Olá {nome}, sua aula é amanhã às {hora_aula}.",
      isDefault: true,
    });
    expect(result).toEqual({ success: true });
    expect(db.insert).toHaveBeenCalled();
  });
});

describe("reminderTemplates.delete", () => {
  it("deletes a template", async () => {
    const db = makeDb();
    (getDb as ReturnType<typeof vi.fn>).mockResolvedValue(db);
    const caller = appRouter.createCaller(makeCtx());
    const result = await caller.reminderTemplates.delete({ id: 1 });
    expect(result).toEqual({ success: true });
    expect(db.delete).toHaveBeenCalled();
  });
});

describe("paymentDues.list", () => {
  it("returns empty array when db is unavailable", async () => {
    (getDb as ReturnType<typeof vi.fn>).mockResolvedValue(null);
    const caller = appRouter.createCaller(makeCtx());
    const list = await caller.paymentDues.list();
    expect(list).toEqual([]);
  });
});

describe("paymentDues.markPaid", () => {
  it("marks a payment as paid and cancels related reminders", async () => {
    const db = makeDb();
    (getDb as ReturnType<typeof vi.fn>).mockResolvedValue(db);
    const caller = appRouter.createCaller(makeCtx());
    const result = await caller.paymentDues.markPaid({ id: 5 });
    expect(result).toEqual({ success: true });
    // update should be called twice: once for paymentDues, once for reminders
    expect(db.update).toHaveBeenCalledTimes(2);
  });
});

describe("paymentDues.overdue", () => {
  it("returns empty array when db is unavailable", async () => {
    (getDb as ReturnType<typeof vi.fn>).mockResolvedValue(null);
    const caller = appRouter.createCaller(makeCtx());
    const result = await caller.paymentDues.overdue();
    expect(result).toEqual([]);
  });

  it("returns overdue payments from db", async () => {
    const overdueRows = [
      { id: 1, studentId: 1, amount: 150, dueDate: "2026-01-01", status: "pendente", month: 1, year: 2026, studentName: "João Silva", studentPhone: "11999999999" },
    ];
    const db = makeDb({
      orderBy: vi.fn().mockResolvedValue(overdueRows),
    });
    (getDb as ReturnType<typeof vi.fn>).mockResolvedValue(db);
    const caller = appRouter.createCaller(makeCtx());
    const result = await caller.paymentDues.overdue();
    expect(result).toEqual(overdueRows);
    expect(db.select).toHaveBeenCalled();
    expect(db.from).toHaveBeenCalled();
    expect(db.where).toHaveBeenCalled();
  });
});
