import 'dotenv/config';
import { getDb } from "../server/db";
import { reminders, lessons, students, settings } from "../drizzle/schema";
import { eq, and, or, sql } from "drizzle-orm";

async function run() {
  console.log("=== INICIANDO VALIDAÇÃO DE LEMBRETES DE AULA REMARCADA ===");
  const db = await getDb();
  if (!db) {
    console.error("Erro: Banco de dados não disponível.");
    process.exit(1);
  }

  // 1. Obter ou Criar Organização / Professor / Aluno de Teste
  // Usaremos os registros existentes do usuário walysson (id 163 ou semelhante se disponível)
  // Mas para garantir isolamento e evitar quebrar dados de produção, vamos buscar um aluno ativo existente
  const [activeStudent] = await db.select({
    id: students.id,
    userId: students.userId,
    organizationId: students.organizationId,
    name: students.name,
  }).from(students).where(eq(students.status, "ativo")).limit(1);

  if (!activeStudent) {
    console.error("Erro: Nenhum aluno ativo encontrado para teste.");
    process.exit(1);
  }

  const orgId = activeStudent.organizationId;
  const userId = activeStudent.userId;
  const studentId = activeStudent.id;

  console.log(`Usando aluno de teste: ID=${studentId}, Name=${activeStudent.name}, OrgID=${orgId}, UserID=${userId}`);

  // Limpeza de testes anteriores (se houver)
  await db.delete(reminders).where(and(eq(reminders.studentId, studentId), sql`message LIKE '%[TESTE DE AGENDAMENTO]%'`));
  await db.delete(lessons).where(and(eq(lessons.studentId, studentId), sql`title LIKE '%[TESTE DE AGENDAMENTO]%'`));

  // 2. Criar uma aula agendada para HOJE às 18:00
  const today = new Date();
  const lessonDate = new Date(today.getFullYear(), today.getMonth(), today.getDate(), 18, 0, 0);
  console.log(`Criando aula de teste para hoje: ${lessonDate.toISOString()}`);

  const [insertedLesson] = await db.insert(lessons).values({
    organizationId: orgId,
    userId: userId,
    studentId: studentId,
    title: "[TESTE DE AGENDAMENTO] Aula de Música",
    scheduledAt: lessonDate,
    duration: 60,
    status: "agendada",
    createdAt: new Date(),
    updatedAt: new Date()
  }).returning({ id: lessons.id });

  const lessonId = insertedLesson.id;
  console.log(`Aula criada com ID: ${lessonId}`);

  // 3. Simular geração de lembretes (Job de Automação)
  console.log("Simulando geração de lembretes automática para a data de hoje...");
  const dateStr = lessonDate.toISOString().slice(0, 10);
  const ref24h = `lesson-24h-${lessonId}-${dateStr}`;
  const ref1h = `lesson-1h-${lessonId}-${lessonDate.getTime()}`;

  // Inserir os lembretes simulando o comportamento do runAutomation
  // (Pois a aula é hoje às 18:00, logo time24h = ontem às 18:00 <= now, então o de 24h já deveria ter sido gerado)
  const time24h = new Date(lessonDate.getTime() - 24 * 60 * 60 * 1000);
  await db.insert(reminders).values({
    organizationId: orgId,
    userId: userId,
    studentId: studentId,
    lessonId: lessonId,
    type: "aula",
    message: "[TESTE DE AGENDAMENTO] Lembrete 24h: Sua aula é amanhã às 18:00.",
    scheduledAt: time24h,
    status: "pendente",
    autoGenerated: 1,
    refId: ref24h,
  });

  console.log(`Lembrete 24h inserido pendente com refId: ${ref24h}`);

  // 4. Remarcar a aula para AMANHÃ no mesmo horário (18:00)
  const tomorrowDate = new Date(lessonDate.getTime() + 24 * 60 * 60 * 1000);
  console.log(`Remarcando a aula para amanhã: ${tomorrowDate.toISOString()}`);

  // Vamos atualizar utilizando a lógica que implementamos no router
  // (Cancelamento imediato dos pendentes)
  // Simulando a execução do update no DB
  await db.update(lessons).set({
    scheduledAt: tomorrowDate,
    updatedAt: new Date()
  }).where(eq(lessons.id, lessonId));

  // Aciona o cancelamento implementado
  await db.update(reminders)
    .set({ status: 'cancelado', cancelledAt: new Date(), updatedAt: new Date() })
    .where(and(
      eq(reminders.lessonId, lessonId),
      eq(reminders.status, 'pendente')
    ));

  // 5. Verificar se o lembrete antigo foi de fato cancelado
  const oldReminders = await db.select().from(reminders).where(eq(reminders.refId, ref24h));
  console.log("Status do lembrete antigo pós-remarcação:", oldReminders.map(r => ({ id: r.id, status: r.status, refId: r.refId })));
  
  if (oldReminders.length === 1 && oldReminders[0].status === "cancelado") {
    console.log("✔ SUCESSO: O lembrete antigo foi corretamente marcado como 'cancelado'!");
  } else {
    console.error("❌ ERRO: O lembrete antigo não foi cancelado ou não foi encontrado.");
  }

  // 6. Verificar se um novo lembrete pode ser gerado para a nova data
  console.log("Simulando geração de lembrete para a nova data (amanhã)...");
  const newDateStr = tomorrowDate.toISOString().slice(0, 10);
  const newRef24h = `lesson-24h-${lessonId}-${newDateStr}`;
  const newTime24h = new Date(tomorrowDate.getTime() - 24 * 60 * 60 * 1000);

  // Fazer a query de duplicação que está em automationJob.ts
  const existing24 = await db.select({ id: reminders.id })
    .from(reminders)
    .where(
      and(
        eq(reminders.organizationId, orgId),
        or(
          eq(reminders.refId, newRef24h),
          eq(reminders.refId, `lesson-${lessonId}-${newDateStr}`),
          and(
            eq(reminders.refId, `lesson-24h-${lessonId}`),
            sql`abs(extract(epoch from (${reminders.scheduledAt} - ${newTime24h.toISOString()}::timestamp))) < 43200`
          )
        )
      )
    )
    .limit(1);

  console.log(`Deduplicação encontrou ${existing24.length} registros para a nova data.`);

  if (existing24.length === 0) {
    console.log("✔ SUCESSO: Nenhum registro duplicado encontrado para a nova data! O novo lembrete pode ser gerado normalmente.");
    
    // Inserir o novo lembrete
    await db.insert(reminders).values({
      organizationId: orgId,
      userId: userId,
      studentId: studentId,
      lessonId: lessonId,
      type: "aula",
      message: "[TESTE DE AGENDAMENTO] Lembrete 24h: Sua aula é amanhã às 18:00 (nova data).",
      scheduledAt: newTime24h,
      status: "pendente",
      autoGenerated: 1,
      refId: newRef24h,
    });
    console.log("Novo lembrete inserido com sucesso!");
  } else {
    console.error("❌ ERRO: A checagem de duplicidade acusou falso-positivo para a nova data da aula remarcada.");
  }

  // Limpeza final de registros de teste
  console.log("Limpando registros de teste...");
  await db.delete(reminders).where(and(eq(reminders.studentId, studentId), sql`message LIKE '%[TESTE DE AGENDAMENTO]%'`));
  await db.delete(lessons).where(and(eq(lessons.studentId, studentId), sql`title LIKE '%[TESTE DE AGENDAMENTO]%'`));
  console.log("Limpeza concluída.");
  console.log("=== FIM DA VALIDAÇÃO DE LEMBRETES ===");
}

run().then(() => process.exit(0)).catch(err => {
  console.error("Erro durante a execução do script de validação:", err);
  process.exit(1);
});
