/**
 * Asaas Payment Service
 * Handles all communication with the Asaas API (PIX & Credit Card)
 */

import { ENV } from "../_core/env";

const headers = () => ({
  "Content-Type": "application/json",
  access_token: ENV.asaasApiKey,
});

// ─── Security Lock ────────────────────────────────────────────────────────────

export const ASAAS_ENABLED_EMAIL = 'wrmusic762@gmail.com';

export function isAsaasEnabled(email?: string | null): boolean {
  return email === ASAAS_ENABLED_EMAIL;
}

// ─── Types ───────────────────────────────────────────────────────────────────

export type AsaasBillingType = "PIX" | "CREDIT_CARD";

export interface AsaasCustomer {
  id: string;
  name: string;
  email?: string;
  cpfCnpj?: string;
  phone?: string;
}

export interface AsaasCharge {
  id: string;
  status: string;
  invoiceUrl: string;      // Link para pagamento Boleto/Cartão
  pixQrCode?: string;      // QR code PIX (base64)
  pixCopiaECola?: string;  // Chave PIX copia-e-cola
  billingType: AsaasBillingType;
  value: number;
  dueDate: string;
  description?: string;
}

// ─── Customer ────────────────────────────────────────────────────────────────

/**
 * Creates a new customer on Asaas.
 * Returns the customer ID generated by Asaas.
 */
export async function createAsaasCustomer(params: {
  name: string;
  email?: string;
  phone?: string;
  cpfCnpj?: string;
}): Promise<string> {
  console.log(`[Asaas] Criando cliente no ambiente: ${ENV.asaasBaseUrl}`);
  const res = await fetch(`${ENV.asaasBaseUrl}/customers`, {
    method: "POST",
    headers: headers(),
    body: JSON.stringify({
      name: params.name,
      email: params.email,
      phone: params.phone,
      cpfCnpj: params.cpfCnpj,
      notificationDisabled: false,
    }),
  });

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`[Asaas] Erro ao criar cliente: ${res.status} ${body}`);
  }

  const data = await res.json() as AsaasCustomer;
  return data.id;
}

// ─── Charge ──────────────────────────────────────────────────────────────────

/**
 * Creates a charge (PIX or Credit Card) on Asaas.
 */
export async function createAsaasCharge(params: {
  asaasCustomerId: string;
  billingType: AsaasBillingType;
  value: number;
  dueDate: string; // "YYYY-MM-DD"
  description?: string;
}): Promise<AsaasCharge> {
  console.log(`[Asaas] Criando cobrança no ambiente: ${ENV.asaasBaseUrl}`);
  const res = await fetch(`${ENV.asaasBaseUrl}/payments`, {
    method: "POST",
    headers: headers(),
    body: JSON.stringify({
      customer: params.asaasCustomerId,
      billingType: params.billingType,
      value: params.value,
      dueDate: params.dueDate,
      description: params.description ?? "Mensalidade MusicPro",
      // PIX expires in 30 days; credit card shows payment link
    }),
  });

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`[Asaas] Erro ao criar cobrança: ${res.status} ${body}`);
  }

  return res.json() as Promise<AsaasCharge>;
}

/**
 * Retrieves PIX QR Code details for an existing charge.
 */
export async function getAsaasPixQrCode(asaasPaymentId: string): Promise<{
  encodedImage: string;
  payload: string;
  expirationDate: string;
}> {
  const res = await fetch(`${ENV.asaasBaseUrl}/payments/${asaasPaymentId}/pixQrCode`, {
    method: "GET",
    headers: headers(),
  });

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`[Asaas] Erro ao buscar QR Code PIX: ${res.status} ${body}`);
  }

  return res.json();
}

/**
 * Deletes/cancels an existing charge on Asaas.
 */
export async function deleteAsaasCharge(asaasPaymentId: string): Promise<void> {
  const res = await fetch(`${ENV.asaasBaseUrl}/payments/${asaasPaymentId}`, {
    method: "DELETE",
    headers: headers(),
  });

  if (!res.ok && res.status !== 404) {
    const body = await res.text();
    throw new Error(`[Asaas] Erro ao cancelar cobrança: ${res.status} ${body}`);
  }
}

/**
 * Retrieves the current status of a charge.
 */
export async function getAsaasChargeStatus(asaasPaymentId: string): Promise<string> {
  const res = await fetch(`${ENV.asaasBaseUrl}/payments/${asaasPaymentId}`, {
    method: "GET",
    headers: headers(),
  });

  if (!res.ok) {
    throw new Error(`[Asaas] Erro ao buscar status: ${res.status}`);
  }

  const data = await res.json() as AsaasCharge;
  return data.status;
}
