/**
 * Asaas Payment Service
 * Handles all communication with the Asaas API (PIX & Credit Card)
 *
 * FIXES aplicados:
 * - ALTO-1: Timeout de 15s em todas as chamadas fetch (AbortController)
 * - ALTO-3: updateAsaasSubscription faz merge com estado atual antes de atualizar
 * - Logging estruturado com tempo de execução em todos os endpoints
 */

import { ENV } from "../_core/env";

const headers = (apiKey?: string) => ({
  "Content-Type": "application/json",
  access_token: apiKey || ENV.asaasApiKey,
});

// ─── ALTO-1 FIX: fetch com timeout de 15 segundos ────────────────────────────
function asaasFetch(url: string, options: RequestInit): Promise<Response> {
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), 15_000); // 15s
  return fetch(url, { ...options, signal: controller.signal })
    .finally(() => clearTimeout(timeoutId));
}

// ─── Logging estruturado ──────────────────────────────────────────────────────
async function asaasRequest(
  method: string,
  url: string,
  body?: object,
  apiKey?: string
): Promise<Response> {
  const start = Date.now();
  const shortUrl = url.replace(ENV.asaasBaseUrl, "");
  console.log(`[Asaas] → ${method} ${shortUrl}`, body ? JSON.stringify(body) : "");
  try {
    const res = await asaasFetch(url, {
      method,
      headers: headers(apiKey),
      body: body ? JSON.stringify(body) : undefined,
    });
    console.log(`[Asaas] ← ${res.status} ${shortUrl} (${Date.now() - start}ms)`);
    return res;
  } catch (err: any) {
    const isTimeout = err?.name === "AbortError";
    console.error(`[Asaas] ✗ ${method} ${shortUrl} — ${isTimeout ? "TIMEOUT (15s)" : err.message} (${Date.now() - start}ms)`);
    throw isTimeout
      ? new Error(`[Asaas] Timeout ao chamar ${shortUrl}. A API do Asaas não respondeu em 15 segundos.`)
      : err;
  }
}

// ─── Security Lock ─────────────────────────────────────────────────────────────
export function isAsaasEnabled(email?: string | null): boolean {
  return !!ENV.asaasApiKey;
}

// ─── Types ────────────────────────────────────────────────────────────────────

export type AsaasBillingType = "PIX" | "CREDIT_CARD" | "UNDEFINED";

export interface AsaasCustomer {
  id: string;
  name: string;
  email?: string;
  cpfCnpj?: string;
  phone?: string;
}

export interface AsaasCharge {
  id: string;
  status: string;
  invoiceUrl: string;      // Link para pagamento Boleto/Cartão
  pixQrCode?: string;      // QR code PIX (base64)
  pixCopiaECola?: string;  // Chave PIX copia-e-cola
  billingType: AsaasBillingType;
  value: number;
  dueDate: string;
  description?: string;
}

export interface AsaasSubscription {
  id: string;
  status: string;
  nextDueDate: string;
  billingType: AsaasBillingType;
  value: number;
  cycle: "MONTHLY" | "YEARLY";
  description: string;
  checkoutUrl?: string;
}

// ─── Customer ─────────────────────────────────────────────────────────────────

/**
 * Creates a new customer on Asaas.
 * Returns the customer ID generated by Asaas.
 */
export async function createAsaasCustomer(params: {
  name: string;
  email?: string;
  phone?: string;
  cpfCnpj?: string;
}, apiKey?: string): Promise<string> {
  const res = await asaasRequest(
    "POST",
    `${ENV.asaasBaseUrl}/customers`,
    {
      name: params.name,
      email: params.email,
      phone: params.phone,
      cpfCnpj: params.cpfCnpj,
      notificationDisabled: false,
    },
    apiKey
  );

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`[Asaas] Erro ao criar cliente: ${res.status} ${body}`);
  }

  const data = await res.json() as AsaasCustomer;
  return data.id;
}

// ─── Charge ───────────────────────────────────────────────────────────────────

/**
 * Creates a charge (PIX or Credit Card) on Asaas.
 */
export async function createAsaasCharge(params: {
  asaasCustomerId: string;
  billingType: AsaasBillingType;
  value: number;
  dueDate: string; // "YYYY-MM-DD"
  description?: string;
}, apiKey?: string): Promise<AsaasCharge> {
  const res = await asaasRequest(
    "POST",
    `${ENV.asaasBaseUrl}/payments`,
    {
      customer: params.asaasCustomerId,
      billingType: params.billingType,
      value: params.value,
      dueDate: params.dueDate,
      description: params.description ?? "Mensalidade MusicPro",
    },
    apiKey
  );

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`[Asaas] Erro ao criar cobrança: ${res.status} ${body}`);
  }

  return res.json() as Promise<AsaasCharge>;
}

/**
 * Retrieves PIX QR Code details for an existing charge.
 */
export async function getAsaasPixQrCode(asaasPaymentId: string, apiKey?: string): Promise<{
  encodedImage: string;
  payload: string;
  expirationDate: string;
}> {
  const res = await asaasRequest(
    "GET",
    `${ENV.asaasBaseUrl}/payments/${asaasPaymentId}/pixQrCode`,
    undefined,
    apiKey
  );

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`[Asaas] Erro ao buscar QR Code PIX: ${res.status} ${body}`);
  }

  return res.json();
}

/**
 * Deletes/cancels an existing charge on Asaas.
 * 404 is treated as success (already deleted).
 */
export async function deleteAsaasCharge(asaasPaymentId: string, apiKey?: string): Promise<void> {
  const res = await asaasRequest(
    "DELETE",
    `${ENV.asaasBaseUrl}/payments/${asaasPaymentId}`,
    undefined,
    apiKey
  );

  // 404 = já foi deletado anteriormente, considerar como sucesso
  if (!res.ok && res.status !== 404) {
    const body = await res.text();
    throw new Error(`[Asaas] Erro ao cancelar cobrança: ${res.status} ${body}`);
  }
}

export async function getAsaasChargeStatus(asaasPaymentId: string, apiKey?: string): Promise<string> {
  const res = await asaasRequest(
    "GET",
    `${ENV.asaasBaseUrl}/payments/${asaasPaymentId}`,
    undefined,
    apiKey
  );

  if (!res.ok) {
    throw new Error(`[Asaas] Erro ao buscar status da cobrança: ${res.status}`);
  }

  const data = await res.json() as AsaasCharge;
  return data.status;
}

// ─── Subscription ─────────────────────────────────────────────────────────────

export async function createAsaasSubscription(params: {
  customer: string;
  billingType: AsaasBillingType;
  value: number;
  nextDueDate: string;
  cycle: "MONTHLY" | "YEARLY";
  description: string;
  successUrl?: string;
}, apiKey?: string) {
  const res = await asaasRequest(
    "POST",
    `${ENV.asaasBaseUrl}/subscriptions`,
    {
      customer: params.customer,
      billingType: params.billingType,
      value: params.value,
      nextDueDate: params.nextDueDate,
      cycle: params.cycle,
      description: params.description,
      successUrl: params.successUrl,
    },
    apiKey
  );

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`[Asaas] Erro ao criar assinatura: ${res.status} ${body}`);
  }

  return res.json() as Promise<AsaasSubscription>;
}

export async function getAsaasSubscriptionPayments(subscriptionId: string, apiKey?: string): Promise<AsaasCharge[]> {
  const res = await asaasRequest(
    "GET",
    `${ENV.asaasBaseUrl}/subscriptions/${subscriptionId}/payments`,
    undefined,
    apiKey
  );

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`[Asaas] Erro ao buscar pagamentos da assinatura: ${res.status} ${body}`);
  }

  const data = await res.json() as { data: AsaasCharge[] };
  return data.data ?? [];
}

export async function getAsaasSubscription(subscriptionId: string, apiKey?: string): Promise<AsaasSubscription> {
  const res = await asaasRequest(
    "GET",
    `${ENV.asaasBaseUrl}/subscriptions/${subscriptionId}`,
    undefined,
    apiKey
  );

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`[Asaas] Erro ao buscar assinatura: ${res.status} ${body}`);
  }

  return res.json() as Promise<AsaasSubscription>;
}

/**
 * ALTO-3 FIX: Busca o estado atual antes de atualizar para não zerar campos não enviados.
 */
export async function updateAsaasSubscription(subscriptionId: string, params: {
  value?: number;
  description?: string;
  cycle?: "MONTHLY" | "YEARLY";
}, apiKey?: string) {
  // Buscar estado atual para fazer merge seguro
  let currentSub: Partial<AsaasSubscription> = {};
  try {
    currentSub = await getAsaasSubscription(subscriptionId, apiKey);
  } catch {
    // Se não conseguir buscar, tenta atualizar com o que tem
    console.warn(`[Asaas] Não foi possível buscar estado atual da assinatura ${subscriptionId} para merge`);
  }

  // Merge: preserva campos existentes, sobrescreve apenas os enviados
  const mergedBody = {
    billingType: currentSub.billingType,
    value: currentSub.value,
    cycle: currentSub.cycle,
    description: currentSub.description,
    nextDueDate: currentSub.nextDueDate,
    ...params, // sobrescreve com os novos valores
  };

  const res = await asaasRequest(
    "POST",
    `${ENV.asaasBaseUrl}/subscriptions/${subscriptionId}`,
    mergedBody,
    apiKey
  );

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`[Asaas] Erro ao atualizar assinatura: ${res.status} ${body}`);
  }

  return res.json() as Promise<AsaasSubscription>;
}

export async function deleteAsaasSubscription(subscriptionId: string, apiKey?: string) {
  const res = await asaasRequest(
    "DELETE",
    `${ENV.asaasBaseUrl}/subscriptions/${subscriptionId}`,
    undefined,
    apiKey
  );

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`[Asaas] Erro ao cancelar assinatura: ${res.status} ${body}`);
  }

  return res.json() as Promise<{ deleted: boolean; id: string }>;
}
